# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm --prefix wp-content/themes/gsc/package.json install
      - run: npm npm --prefix wp-content/themes/gsc/package.json run-script build
      - uses: EndBug/add-and-commit@v5
        with:
          author_name: Brenda Rossi
          author_email: brenda@gravityswitch.com
          message: "Compile assets"
          add: "*.js *.css"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy!
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: ${{ secrets.FTP_SERVER_DIR }}
          METHOD: ${{ secrets.FTP_PROTOCOL }}
          PORT: ${{ secrets.FTP_PORT }}
          ARGS: --verbose  
